version: 2.1

orbs:
  docker: circleci/docker@1.4.0

commands:
  build_push:
    description: "Builds and pushes a docker image to docker hub"
    parameters:
      service-name:
        type: string
      dockerfile-name:
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - docker/check:
          docker-username: DOCKERHUB_LOGIN
          docker-password: DOCKERHUB_PASSWORD
      # - run:
      #     name: Login to Docker hub
      #     command: |
      #       docker login -username=mmcken3 --password=${DOCKERHUB_PASSWORD}
      - run:
          name: Build and tag
          command: |
            docker build -t <<parameters.service-name>> -f ./docker/<<parameters.dockerfile-name>>.dockerfile .
            # docker tag <<parameters.service-name>>:latest <<parameters.service-name>>:${CIRCLE_TAG}
            docker tag <<parameters.service-name>>:latest <<parameters.service-name>>:test
            docker build -t <<parameters.service-name>> -f ./docker/<<parameters.dockerfile-name>>.dockerfile
      - run:
          name: Push image to docker hub
          command: |
            docker push <<parameters.service-name>>:latest
            # docker push <<parameters.service-name>>:${CIRCLE_TAG}
            docker push <<parameters.service-name>>:test

jobs:
  api_build:
    docker: 
      - image: circleci/python:3.6.4
    steps:
      - build_push:
          service-name: "mawburn/portaler"
          dockerfile-name: "api"
  bot_build:
    docker: 
      - image: circleci/python:3.6.4
    steps:
      - build_push:
          service-name: "mawburn/portaler-bot"
          dockerfile-name: "bot"

workflows:
  version: 2
  portaler:
      jobs:
        - api_build:
            filters:
              branches:
                only:
                  - feature/ci
        # - bot_build
        # can add local build here at the end with depends on the other two to force it to be last
