on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          src_path: /.
          dst_path: /.
          dst_repo_name: portaler-zone/portaler-core
          dst_branch: netlify
          clean: true
          exclude: */api-server/*
